// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: cosmos.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace CosmosProto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class InterfaceDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScalarDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"field_type", IsPacked = true)]
        public global::System.Collections.Generic.List<ScalarType> FieldTypes { get; } = new global::System.Collections.Generic.List<ScalarType>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ScalarType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SCALAR_TYPE_UNSPECIFIED")]
        ScalarTypeUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SCALAR_TYPE_STRING")]
        ScalarTypeString = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SCALAR_TYPE_BYTES")]
        ScalarTypeBytes = 2,
    }

    public static class Extensions
    {
        public static global::System.Collections.Generic.IEnumerable<string> GetImplementsInterfaces(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? null : global::ProtoBuf.Extensible.GetValues<string>(obj, 93001);

        public static void AddImplementsInterfaces(this global::Google.Protobuf.Reflection.MessageOptions obj, string value)
            => global::ProtoBuf.Extensible.AppendValue<string>(obj, 93001, value);

        public static string GetAcceptsInterface(this global::Google.Protobuf.Reflection.FieldOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<string>(obj, 93001);

        public static void SetAcceptsInterface(this global::Google.Protobuf.Reflection.FieldOptions obj, string value)
            => global::ProtoBuf.Extensible.AppendValue<string>(obj, 93001, value);

        public static string GetScalar(this global::Google.Protobuf.Reflection.FieldOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<string>(obj, 93002);

        public static void SetScalar(this global::Google.Protobuf.Reflection.FieldOptions obj, string value)
            => global::ProtoBuf.Extensible.AppendValue<string>(obj, 93002, value);

        public static global::System.Collections.Generic.IEnumerable<InterfaceDescriptor> GetDeclareInterfaces(this global::Google.Protobuf.Reflection.FileOptions obj)
            => obj == null ? null : global::ProtoBuf.Extensible.GetValues<InterfaceDescriptor>(obj, 793021);

        public static void AddDeclareInterfaces(this global::Google.Protobuf.Reflection.FileOptions obj, InterfaceDescriptor value)
            => global::ProtoBuf.Extensible.AppendValue<InterfaceDescriptor>(obj, 793021, value);

        public static global::System.Collections.Generic.IEnumerable<ScalarDescriptor> GetDeclareScalars(this global::Google.Protobuf.Reflection.FileOptions obj)
            => obj == null ? null : global::ProtoBuf.Extensible.GetValues<ScalarDescriptor>(obj, 793022);

        public static void AddDeclareScalars(this global::Google.Protobuf.Reflection.FileOptions obj, ScalarDescriptor value)
            => global::ProtoBuf.Extensible.AppendValue<ScalarDescriptor>(obj, 793022, value);

    }
}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
