// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: params.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace tendermint.types
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"block")]
        public BlockParams Block { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"evidence")]
        public EvidenceParams Evidence { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"validator")]
        public ValidatorParams Validator { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"version")]
        public VersionParams Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_bytes")]
        public long MaxBytes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"max_gas")]
        public long MaxGas { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_iota_ms")]
        public long TimeIotaMs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EvidenceParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_age_num_blocks")]
        public long MaxAgeNumBlocks { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"max_age_duration")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? MaxAgeDuration { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_bytes")]
        public long MaxBytes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ValidatorParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pub_key_types")]
        public global::System.Collections.Generic.List<string> PubKeyTypes { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VersionParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"app_version")]
        public ulong AppVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HashedParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"block_max_bytes")]
        public long BlockMaxBytes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"block_max_gas")]
        public long BlockMaxGas { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
