// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ibc.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmwasm.wasm.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgIBCSend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"channel")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Channel { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"timeout_height")]
        public ulong TimeoutHeight { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"timeout_timestamp")]
        public ulong TimeoutTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgIBCCloseChannel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"channel")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Channel { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
