// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: types.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmwasm.wasm.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AccessTypeParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public AccessType Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccessConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"permission")]
        public AccessType Permission { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"addresses")]
        public global::System.Collections.Generic.List<string> Addresses { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Params : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code_upload_access")]
        public AccessConfig CodeUploadAccess { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"instantiate_default_permission")]
        public AccessType InstantiateDefaultPermission { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CodeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code_hash")]
        public byte[] CodeHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"creator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Creator { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"instantiate_config")]
        public AccessConfig InstantiateConfig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"creator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Creator { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"created")]
        public AbsoluteTxPosition Created { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ibc_port_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IbcPortId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"extension")]
        public global::Google.Protobuf.WellKnownTypes.Any Extension { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractCodeHistoryEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"operation")]
        public ContractCodeHistoryOperationType Operation { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"updated")]
        public AbsoluteTxPosition Updated { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"msg")]
        public byte[] Msg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbsoluteTxPosition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"block_height")]
        public ulong BlockHeight { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tx_index")]
        public ulong TxIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Model : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public byte[] Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccessType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS_TYPE_UNSPECIFIED")]
        AccessTypeUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS_TYPE_NOBODY")]
        AccessTypeNobody = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS_TYPE_ONLY_ADDRESS")]
        AccessTypeOnlyAddress = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS_TYPE_EVERYBODY")]
        AccessTypeEverybody = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS_TYPE_ANY_OF_ADDRESSES")]
        AccessTypeAnyOfAddresses = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ContractCodeHistoryOperationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED")]
        ContractCodeHistoryOperationTypeUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT")]
        ContractCodeHistoryOperationTypeInit = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE")]
        ContractCodeHistoryOperationTypeMigrate = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS")]
        ContractCodeHistoryOperationTypeGenesis = 3,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
