name: aura_wallet_example
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #network
  dio: ^5.1.2
  retrofit: ^4.0.1

  #tools
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  #helper:
  permission_handler: ^10.2.0
  get_it: ^7.6.0
  qr_flutter: ^4.1.0
  intl: ^0.18.0

  #state management:
  flutter_bloc: ^8.1.3

  #ui
  shimmer: ^3.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #aura_sdk:
  aura_sdk:
    path: ../aura_sdk

  #core
  base_response:
    path: cores/base_response
  base_exception_wrapper:
    path: cores/base_exception_wrapper

  #package helper
  mobile_scanner:
    path: packages/mobile_scanner

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  retrofit_generator: ^7.0.1
  freezed: ^2.3.4
  json_serializable: ^6.7.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/language/
