// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: slashing.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.slashing.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ValidatorSigningInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"start_height")]
        public long StartHeight { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"index_offset")]
        public long IndexOffset { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"jailed_until")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? JailedUntil { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"tombstoned")]
        public bool Tombstoned { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"missed_blocks_counter")]
        public long MissedBlocksCounter { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Params : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signed_blocks_window")]
        public long SignedBlocksWindow { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"min_signed_per_window")]
        public byte[] MinSignedPerWindow { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"downtime_jail_duration")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? DowntimeJailDuration { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"slash_fraction_double_sign")]
        public byte[] SlashFractionDoubleSign { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"slash_fraction_downtime")]
        public byte[] SlashFractionDowntime { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
