// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: msg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.msg.v1
{

    public static partial class Extensions
    {
        public static global::System.Collections.Generic.IEnumerable<string> GetSigners(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? null : global::ProtoBuf.Extensible.GetValues<string>(obj, 11110000);

        public static void AddSigners(this global::Google.Protobuf.Reflection.MessageOptions obj, string value)
            => global::ProtoBuf.Extensible.AppendValue<string>(obj, 11110000, value);

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
