// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: genesis.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.gov.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GenesisState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"starting_proposal_id")]
        public ulong StartingProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"deposits")]
        public global::System.Collections.Generic.List<Deposit> Deposits { get; } = new global::System.Collections.Generic.List<Deposit>();

        [global::ProtoBuf.ProtoMember(3, Name = @"votes")]
        public global::System.Collections.Generic.List<Vote> Votes { get; } = new global::System.Collections.Generic.List<Vote>();

        [global::ProtoBuf.ProtoMember(4, Name = @"proposals")]
        public global::System.Collections.Generic.List<Proposal> Proposals { get; } = new global::System.Collections.Generic.List<Proposal>();

        [global::ProtoBuf.ProtoMember(5, Name = @"deposit_params")]
        public DepositParams DepositParams { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"voting_params")]
        public VotingParams VotingParams { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"tally_params")]
        public TallyParams TallyParams { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
