// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: hd.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.crypto.hd.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BIP44Params : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"purpose")]
        public uint Purpose { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"coin_type")]
        public uint CoinType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"account")]
        public uint Account { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"change")]
        public bool Change { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"address_index")]
        public uint AddressIndex { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
