// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: tx.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.group.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"members")]
        public global::System.Collections.Generic.List<Member> Members { get; } = new global::System.Collections.Generic.List<Member>();

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateGroupResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public ulong GroupId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupMembers : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"member_updates")]
        public global::System.Collections.Generic.List<Member> MemberUpdates { get; } = new global::System.Collections.Generic.List<Member>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupMembersResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupAdmin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"new_admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewAdmin { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupAdminResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupMetadata : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupMetadataResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateGroupPolicy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"decision_policy")]
        public global::Google.Protobuf.WellKnownTypes.Any DecisionPolicy { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateGroupPolicyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupPolicyAdmin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"new_admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewAdmin { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateGroupWithPolicy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"members")]
        public global::System.Collections.Generic.List<Member> Members { get; } = new global::System.Collections.Generic.List<Member>();

        [global::ProtoBuf.ProtoMember(3, Name = @"group_metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GroupMetadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"group_policy_metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GroupPolicyMetadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"group_policy_as_admin")]
        public bool GroupPolicyAsAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"decision_policy")]
        public global::Google.Protobuf.WellKnownTypes.Any DecisionPolicy { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateGroupWithPolicyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"group_policy_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GroupPolicyAddress { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupPolicyAdminResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupPolicyDecisionPolicy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"decision_policy")]
        public global::Google.Protobuf.WellKnownTypes.Any DecisionPolicy { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupPolicyDecisionPolicyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupPolicyMetadata : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateGroupPolicyMetadataResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgSubmitProposal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"proposers")]
        public global::System.Collections.Generic.List<string> Proposers { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"messages")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> Messages { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

        [global::ProtoBuf.ProtoMember(5, Name = @"exec")]
        public Exec Exec { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgSubmitProposalResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgWithdrawProposal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgWithdrawProposalResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgVote : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"voter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Voter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"option")]
        public VoteOption Option { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"exec")]
        public Exec Exec { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgVoteResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgExec : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"signer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Signer { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgExecResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgLeaveGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id")]
        public ulong GroupId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgLeaveGroupResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Exec
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EXEC_UNSPECIFIED")]
        ExecUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXEC_TRY")]
        ExecTry = 1,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
