// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: types.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.group.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Member : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"weight")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Weight { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"added_at", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? AddedAt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Members : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Member> members { get; } = new global::System.Collections.Generic.List<Member>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ThresholdDecisionPolicy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"threshold")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Threshold { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"windows")]
        public DecisionPolicyWindows Windows { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PercentageDecisionPolicy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"percentage")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Percentage { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"windows")]
        public DecisionPolicyWindows Windows { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DecisionPolicyWindows : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"voting_period", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.TimeSpan? VotingPeriod { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"min_execution_period", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.TimeSpan? MinExecutionPeriod { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GroupInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"version")]
        public ulong Version { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"total_weight")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TotalWeight { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"created_at", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? CreatedAt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GroupMember : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"member")]
        public Member Member { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GroupPolicyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id")]
        public ulong GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"version")]
        public ulong Version { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"decision_policy")]
        public global::Google.Protobuf.WellKnownTypes.Any DecisionPolicy { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"created_at", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? CreatedAt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Proposal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"proposers")]
        public global::System.Collections.Generic.List<string> Proposers { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"submit_time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? SubmitTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"group_version")]
        public ulong GroupVersion { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"group_policy_version")]
        public ulong GroupPolicyVersion { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"status")]
        public ProposalStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"result")]
        public ProposalResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"final_tally_result")]
        public TallyResult FinalTallyResult { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"voting_period_end", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? VotingPeriodEnd { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"executor_result")]
        public ProposalExecutorResult ExecutorResult { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"messages")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> Messages { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TallyResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"yes_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string YesCount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"abstain_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AbstainCount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"no_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NoCount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"no_with_veto_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NoWithVetoCount { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vote : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"voter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Voter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"option")]
        public VoteOption Option { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"submit_time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? SubmitTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum VoteOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_UNSPECIFIED")]
        VoteOptionUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_YES")]
        VoteOptionYes = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_ABSTAIN")]
        VoteOptionAbstain = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_NO")]
        VoteOptionNo = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_NO_WITH_VETO")]
        VoteOptionNoWithVeto = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ProposalStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_UNSPECIFIED")]
        ProposalStatusUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_SUBMITTED")]
        ProposalStatusSubmitted = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_CLOSED")]
        ProposalStatusClosed = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_ABORTED")]
        ProposalStatusAborted = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_WITHDRAWN")]
        ProposalStatusWithdrawn = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ProposalResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_RESULT_UNSPECIFIED")]
        ProposalResultUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_RESULT_UNFINALIZED")]
        ProposalResultUnfinalized = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_RESULT_ACCEPTED")]
        ProposalResultAccepted = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_RESULT_REJECTED")]
        ProposalResultRejected = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ProposalExecutorResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_EXECUTOR_RESULT_UNSPECIFIED")]
        ProposalExecutorResultUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_EXECUTOR_RESULT_NOT_RUN")]
        ProposalExecutorResultNotRun = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_EXECUTOR_RESULT_SUCCESS")]
        ProposalExecutorResultSuccess = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_EXECUTOR_RESULT_FAILURE")]
        ProposalExecutorResultFailure = 3,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
