// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: authz.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.staking.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StakeAuthorization : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_tokens")]
        public global::cosmos._base.v1beta1.Coin MaxTokens { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allow_list")]
        public Validators AllowList
        {
            get => __pbn__validators.Is(2) ? ((Validators)__pbn__validators.Object) : default;
            set => __pbn__validators = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeAllowList() => __pbn__validators.Is(2);
        public void ResetAllowList() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__validators, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__validators;

        [global::ProtoBuf.ProtoMember(3, Name = @"deny_list")]
        public Validators DenyList
        {
            get => __pbn__validators.Is(3) ? ((Validators)__pbn__validators.Object) : default;
            set => __pbn__validators = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeDenyList() => __pbn__validators.Is(3);
        public void ResetDenyList() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__validators, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"authorization_type")]
        public AuthorizationType AuthorizationType { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Validators : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"address")]
            public global::System.Collections.Generic.List<string> Addresses { get; } = new global::System.Collections.Generic.List<string>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AuthorizationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHORIZATION_TYPE_UNSPECIFIED")]
        AuthorizationTypeUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHORIZATION_TYPE_DELEGATE")]
        AuthorizationTypeDelegate = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHORIZATION_TYPE_UNDELEGATE")]
        AuthorizationTypeUndelegate = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHORIZATION_TYPE_REDELEGATE")]
        AuthorizationTypeRedelegate = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
