// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: tx.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.vesting.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateVestingAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"from_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"to_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"amount")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Amounts { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(4, Name = @"end_time")]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"delayed")]
        public bool Delayed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreateVestingAccountResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreatePermanentLockedAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"from_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"to_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"amount")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Amounts { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreatePermanentLockedAccountResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreatePeriodicVestingAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"from_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"to_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"start_time")]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"vesting_periods")]
        public global::System.Collections.Generic.List<Period> VestingPeriods { get; } = new global::System.Collections.Generic.List<Period>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgCreatePeriodicVestingAccountResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
