// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: nft.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.nft.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Class : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"symbol")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Symbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"uri_hash")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UriHash { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"data")]
        public global::Google.Protobuf.WellKnownTypes.Any Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"NFT")]
    public partial class Nft : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"class_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClassId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"uri_hash")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UriHash { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"data")]
        public global::Google.Protobuf.WellKnownTypes.Any Data { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
