// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: listening.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos._base.store.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreKVPair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"store_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StoreKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"delete")]
        public bool Delete { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"key")]
        public byte[] Key { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"value")]
        public byte[] Value { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
