// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: record.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.crypto.keyring.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Record : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"pub_key")]
        public global::Google.Protobuf.WellKnownTypes.Any PubKey { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Local local
        {
            get { return __pbn__item.Is(3) ? ((Local)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializelocal() => __pbn__item.Is(3);
        public void Resetlocal() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__item;

        [global::ProtoBuf.ProtoMember(4)]
        public Ledger ledger
        {
            get { return __pbn__item.Is(4) ? ((Ledger)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeledger() => __pbn__item.Is(4);
        public void Resetledger() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public Multi multi
        {
            get { return __pbn__item.Is(5) ? ((Multi)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializemulti() => __pbn__item.Is(5);
        public void Resetmulti() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public Offline offline
        {
            get { return __pbn__item.Is(6) ? ((Offline)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeoffline() => __pbn__item.Is(6);
        public void Resetoffline() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 6);

        [global::ProtoBuf.ProtoContract()]
        public partial class Local : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"priv_key")]
            public global::Google.Protobuf.WellKnownTypes.Any PrivKey { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"priv_key_type")]
            [global::System.ComponentModel.DefaultValue("")]
            public string PrivKeyType { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Ledger : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"path")]
            public global::cosmos.crypto.hd.v1.BIP44Params Path { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Multi : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Offline : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
