name: aura_mobile_sdk
description: Flutter Aura mobile sdk - Connect coin98 sdk and in app wallet.
version: 0.0.1
homepage: https://github.com/aura-nw/aura-mobile-sdk/tree/main/flutter

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  socket_io_client: ^2.0.1
  uuid: ^4.0.0-beta3-1
  alan: ^0.41.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: aura_mobile_sdk
        pluginClass: AuraConnectSdkPlugin
      ios:
        pluginClass: AuraConnectSdkPlugin
