name: aura_sdk
description: Flutter Coin 98 Connect Sdk.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  socket_io_client: ^2.0.1
  uuid: ^4.0.0-beta3-1
  alan:
    path : packages/alan


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: aura_connect_sdk
        pluginClass: AuraConnectSdkPlugin
      ios:
        pluginClass: AuraConnectSdkPlugin
