// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: feegrant.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace aura.feegrant.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AllowedContractAllowance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"allowance")]
        public global::Google.Protobuf.WellKnownTypes.Any Allowance { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allowed_address")]
        public global::System.Collections.Generic.List<string> AllowedAddresses { get; } = new global::System.Collections.Generic.List<string>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
