// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: types.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace tendermint.p2p
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ProtocolVersion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p2p")]
        public ulong P2p { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"block")]
        public ulong Block { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"app")]
        public ulong App { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"protocol_version")]
        public ProtocolVersion ProtocolVersion { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"node_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NodeId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"listen_addr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ListenAddr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"network")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Network { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Version { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"channels")]
        public byte[] Channels { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"moniker")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Moniker { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"other")]
        public NodeInfoOther Other { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeInfoOther : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tx_index")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TxIndex { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"rpc_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RpcAddress { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"address_info")]
        public global::System.Collections.Generic.List<PeerAddressInfo> AddressInfoes { get; } = new global::System.Collections.Generic.List<PeerAddressInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"last_connected", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? LastConnected { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeerAddressInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"last_dial_success", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? LastDialSuccess { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"last_dial_failure", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? LastDialFailure { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"dial_failures")]
        public uint DialFailures { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
