// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: tx.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.gov.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgSubmitProposal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> Messages { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

        [global::ProtoBuf.ProtoMember(2, Name = @"initial_deposit")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> InitialDeposits { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(3, Name = @"proposer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Proposer { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgSubmitProposalResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgExecLegacyContent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"content")]
        public global::Google.Protobuf.WellKnownTypes.Any Content { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"authority")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Authority { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgExecLegacyContentResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgVote : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"voter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Voter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"option")]
        public VoteOption Option { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgVoteResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgVoteWeighted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"voter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Voter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public global::System.Collections.Generic.List<WeightedVoteOption> Options { get; } = new global::System.Collections.Generic.List<WeightedVoteOption>();

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgVoteWeightedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgDeposit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"depositor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Depositor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"amount")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Amounts { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgDepositResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
