name: base_exception_wrapper
description: Flutter Base User Impact Package
version: 0.0.1
homepage: 'none'

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  base_response:
    path: ../base_response

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
