// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: schema.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.orm.v1alpha1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ModuleSchemaDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"schema_file")]
        public global::System.Collections.Generic.List<FileEntry> SchemaFiles { get; } = new global::System.Collections.Generic.List<FileEntry>();

        [global::ProtoBuf.ProtoMember(2, Name = @"prefix")]
        public byte[] Prefix { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class FileEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            public uint Id { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"proto_file_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ProtoFileName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"storage_type")]
            public StorageType StorageType { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum StorageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_DEFAULT_UNSPECIFIED")]
        StorageTypeDefaultUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_MEMORY")]
        StorageTypeMemory = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_TRANSIENT")]
        StorageTypeTransient = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_INDEX")]
        StorageTypeIndex = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_COMMITMENT")]
        StorageTypeCommitment = 4,
    }

    public static class Extensions
    {
        public static ModuleSchemaDescriptor GetModuleSchema(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<ModuleSchemaDescriptor>(obj, 104503792);

        public static void SetModuleSchema(this global::Google.Protobuf.Reflection.MessageOptions obj, ModuleSchemaDescriptor value)
            => global::ProtoBuf.Extensible.AppendValue<ModuleSchemaDescriptor>(obj, 104503792, value);

    }
}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
