// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: gov.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.gov.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WeightedVoteOption : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"option")]
        public VoteOption Option { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"weight")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Weight { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Deposit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"depositor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Depositor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"amount")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Amounts { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Proposal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"messages")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> Messages { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public ProposalStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"final_tally_result")]
        public TallyResult FinalTallyResult { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"submit_time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? SubmitTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"deposit_end_time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? DepositEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"total_deposit")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> TotalDeposits { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(8, Name = @"voting_start_time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? VotingStartTime { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"voting_end_time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? VotingEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TallyResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"yes_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string YesCount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"abstain_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AbstainCount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"no_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NoCount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"no_with_veto_count")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NoWithVetoCount { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vote : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proposal_id")]
        public ulong ProposalId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"voter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Voter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"options")]
        public global::System.Collections.Generic.List<WeightedVoteOption> Options { get; } = new global::System.Collections.Generic.List<WeightedVoteOption>();

        [global::ProtoBuf.ProtoMember(5, Name = @"metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Metadata { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DepositParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"min_deposit")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> MinDeposits { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(2, Name = @"max_deposit_period", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.TimeSpan? MaxDepositPeriod { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VotingParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"voting_period", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.TimeSpan? VotingPeriod { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TallyParams : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quorum")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Quorum { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"threshold")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Threshold { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"veto_threshold")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VetoThreshold { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum VoteOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_UNSPECIFIED")]
        VoteOptionUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_YES")]
        VoteOptionYes = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_ABSTAIN")]
        VoteOptionAbstain = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_NO")]
        VoteOptionNo = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"VOTE_OPTION_NO_WITH_VETO")]
        VoteOptionNoWithVeto = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ProposalStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_UNSPECIFIED")]
        ProposalStatusUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_DEPOSIT_PERIOD")]
        ProposalStatusDepositPeriod = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_VOTING_PERIOD")]
        ProposalStatusVotingPeriod = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_PASSED")]
        ProposalStatusPassed = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_REJECTED")]
        ProposalStatusRejected = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PROPOSAL_STATUS_FAILED")]
        ProposalStatusFailed = 5,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
