// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: module.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.app.v1alpha1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ModuleDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"go_import")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GoImport { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"use_package")]
        public global::System.Collections.Generic.List<PackageReference> UsePackages { get; } = new global::System.Collections.Generic.List<PackageReference>();

        [global::ProtoBuf.ProtoMember(3, Name = @"can_migrate_from")]
        public global::System.Collections.Generic.List<MigrateFromInfo> CanMigrateFroms { get; } = new global::System.Collections.Generic.List<MigrateFromInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackageReference : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"revision")]
        public uint Revision { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MigrateFromInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"module")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Module { get; set; } = "";

    }

    public static partial class Extensions
    {
        public static ModuleDescriptor GetModule(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<ModuleDescriptor>(obj, 57193479);

        public static void SetModule(this global::Google.Protobuf.Reflection.MessageOptions obj, ModuleDescriptor value)
            => global::ProtoBuf.Extensible.AppendValue<ModuleDescriptor>(obj, 57193479, value);

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
