// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: genesis.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.group.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GenesisState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_seq")]
        public ulong GroupSeq { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"groups")]
        public global::System.Collections.Generic.List<GroupInfo> Groups { get; } = new global::System.Collections.Generic.List<GroupInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"group_members")]
        public global::System.Collections.Generic.List<GroupMember> GroupMembers { get; } = new global::System.Collections.Generic.List<GroupMember>();

        [global::ProtoBuf.ProtoMember(4, Name = @"group_policy_seq")]
        public ulong GroupPolicySeq { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"group_policies")]
        public global::System.Collections.Generic.List<GroupPolicyInfo> GroupPolicies { get; } = new global::System.Collections.Generic.List<GroupPolicyInfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"proposal_seq")]
        public ulong ProposalSeq { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"proposals")]
        public global::System.Collections.Generic.List<Proposal> Proposals { get; } = new global::System.Collections.Generic.List<Proposal>();

        [global::ProtoBuf.ProtoMember(8, Name = @"votes")]
        public global::System.Collections.Generic.List<Vote> Votes { get; } = new global::System.Collections.Generic.List<Vote>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
