// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: tx.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmwasm.wasm.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgStoreCode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"wasm_byte_code")]
        public byte[] WasmByteCode { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"instantiate_permission")]
        public AccessConfig InstantiatePermission { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgStoreCodeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"checksum")]
        public byte[] Checksum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgInstantiateContract : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"msg")]
        public byte[] Msg { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"funds")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Funds { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgInstantiateContract2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Admin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"msg")]
        public byte[] Msg { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"funds")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Funds { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(7, Name = @"salt")]
        public byte[] Salt { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"fix_msg")]
        public bool FixMsg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgInstantiateContractResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgInstantiateContract2Response : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgExecuteContract : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"contract")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Contract { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"msg")]
        public byte[] Msg { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"funds")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Funds { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgExecuteContractResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgMigrateContract : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"contract")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Contract { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"msg")]
        public byte[] Msg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgMigrateContractResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateAdmin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"new_admin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewAdmin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"contract")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Contract { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgUpdateAdminResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgClearAdmin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"contract")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Contract { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgClearAdminResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
