// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: genesis.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmwasm.wasm.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GenesisState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"params")]
        public Params Params { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"codes")]
        public global::System.Collections.Generic.List<Code> Codes { get; } = new global::System.Collections.Generic.List<Code>();

        [global::ProtoBuf.ProtoMember(3, Name = @"contracts")]
        public global::System.Collections.Generic.List<Contract> Contracts { get; } = new global::System.Collections.Generic.List<Contract>();

        [global::ProtoBuf.ProtoMember(4, Name = @"sequences")]
        public global::System.Collections.Generic.List<Sequence> Sequences { get; } = new global::System.Collections.Generic.List<Sequence>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<GenMsgs> gen_msgs { get; } = new global::System.Collections.Generic.List<GenMsgs>();

        [global::ProtoBuf.ProtoContract()]
        public partial class GenMsgs : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"store_code")]
            public MsgStoreCode StoreCode
            {
                get => __pbn__sum.Is(1) ? ((MsgStoreCode)__pbn__sum.Object) : default;
                set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
            }
            public bool ShouldSerializeStoreCode() => __pbn__sum.Is(1);
            public void ResetStoreCode() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 1);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__sum;

            [global::ProtoBuf.ProtoMember(2, Name = @"instantiate_contract")]
            public MsgInstantiateContract InstantiateContract
            {
                get => __pbn__sum.Is(2) ? ((MsgInstantiateContract)__pbn__sum.Object) : default;
                set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeInstantiateContract() => __pbn__sum.Is(2);
            public void ResetInstantiateContract() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 2);

            [global::ProtoBuf.ProtoMember(3, Name = @"execute_contract")]
            public MsgExecuteContract ExecuteContract
            {
                get => __pbn__sum.Is(3) ? ((MsgExecuteContract)__pbn__sum.Object) : default;
                set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeExecuteContract() => __pbn__sum.Is(3);
            public void ResetExecuteContract() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 3);

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Code : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code_id")]
        public ulong CodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code_info")]
        public CodeInfo CodeInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"code_bytes")]
        public byte[] CodeBytes { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pinned")]
        public bool Pinned { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Contract : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"contract_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContractAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"contract_info")]
        public ContractInfo ContractInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"contract_state")]
        public global::System.Collections.Generic.List<Model> ContractStates { get; } = new global::System.Collections.Generic.List<Model>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Sequence : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id_key")]
        public byte[] IdKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public ulong Value { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
