// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: signing.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.tx.signing.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SignatureDescriptors : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signatures")]
        public global::System.Collections.Generic.List<SignatureDescriptor> Signatures { get; } = new global::System.Collections.Generic.List<SignatureDescriptor>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignatureDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"public_key")]
        public global::Google.Protobuf.WellKnownTypes.Any PublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Data data { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"sequence")]
        public ulong Sequence { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Data : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Single single
            {
                get => __pbn__sum.Is(1) ? ((Single)__pbn__sum.Object) : default;
                set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
            }
            public bool ShouldSerializesingle() => __pbn__sum.Is(1);
            public void Resetsingle() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 1);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__sum;

            [global::ProtoBuf.ProtoMember(2)]
            public Multi multi
            {
                get => __pbn__sum.Is(2) ? ((Multi)__pbn__sum.Object) : default;
                set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializemulti() => __pbn__sum.Is(2);
            public void Resetmulti() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 2);

            [global::ProtoBuf.ProtoContract()]
            public partial class Single : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mode")]
                public SignMode Mode { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"signature")]
                public byte[] Signature { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Multi : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"bitarray")]
                public global::cosmos.crypto.multisig.v1beta1.CompactBitArray Bitarray { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"signatures")]
                public global::System.Collections.Generic.List<SignatureDescriptor.Data> Signatures { get; } = new global::System.Collections.Generic.List<SignatureDescriptor.Data>();

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SignMode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SIGN_MODE_UNSPECIFIED")]
        SignModeUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SIGN_MODE_DIRECT")]
        SignModeDirect = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SIGN_MODE_TEXTUAL")]
        SignModeTextual = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SIGN_MODE_DIRECT_AUX")]
        SignModeDirectAux = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SIGN_MODE_LEGACY_AMINO_JSON")]
        SignModeLegacyAminoJson = 127,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
