// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: tx.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.tx.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Tx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body")]
        public TxBody Body { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"auth_info")]
        public AuthInfo AuthInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"signatures")]
        public global::System.Collections.Generic.List<byte[]> Signatures { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TxRaw : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_bytes")]
        public byte[] BodyBytes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"auth_info_bytes")]
        public byte[] AuthInfoBytes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"signatures")]
        public global::System.Collections.Generic.List<byte[]> Signatures { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignDoc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_bytes")]
        public byte[] BodyBytes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"auth_info_bytes")]
        public byte[] AuthInfoBytes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"chain_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChainId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"account_number")]
        public ulong AccountNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignDocDirectAux : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_bytes")]
        public byte[] BodyBytes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"public_key")]
        public global::Google.Protobuf.WellKnownTypes.Any PublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"chain_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChainId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"account_number")]
        public ulong AccountNumber { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sequence")]
        public ulong Sequence { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"tip")]
        public Tip Tip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TxBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> Messages { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

        [global::ProtoBuf.ProtoMember(2, Name = @"memo")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Memo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"timeout_height")]
        public ulong TimeoutHeight { get; set; }

        [global::ProtoBuf.ProtoMember(1023, Name = @"extension_options")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> ExtensionOptions { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

        [global::ProtoBuf.ProtoMember(2047, Name = @"non_critical_extension_options")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any> NonCriticalExtensionOptions { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.WellKnownTypes.Any>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signer_infos")]
        public global::System.Collections.Generic.List<SignerInfo> SignerInfos { get; } = new global::System.Collections.Generic.List<SignerInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"fee")]
        public Fee Fee { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"tip")]
        public Tip Tip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"public_key")]
        public global::Google.Protobuf.WellKnownTypes.Any PublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"mode_info")]
        public ModeInfo ModeInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"sequence")]
        public ulong Sequence { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Single single
        {
            get => __pbn__sum.Is(1) ? ((Single)__pbn__sum.Object) : default;
            set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializesingle() => __pbn__sum.Is(1);
        public void Resetsingle() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__sum;

        [global::ProtoBuf.ProtoMember(2)]
        public Multi multi
        {
            get => __pbn__sum.Is(2) ? ((Multi)__pbn__sum.Object) : default;
            set => __pbn__sum = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializemulti() => __pbn__sum.Is(2);
        public void Resetmulti() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__sum, 2);

        [global::ProtoBuf.ProtoContract()]
        public partial class Single : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"mode")]
            public global::cosmos.tx.signing.v1beta1.SignMode Mode { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Multi : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"bitarray")]
            public global::cosmos.crypto.multisig.v1beta1.CompactBitArray Bitarray { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"mode_infos")]
            public global::System.Collections.Generic.List<ModeInfo> ModeInfos { get; } = new global::System.Collections.Generic.List<ModeInfo>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Fee : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"amount")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Amounts { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(2, Name = @"gas_limit")]
        public ulong GasLimit { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"payer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Payer { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"granter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Granter { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Tip : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"amount")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> Amounts { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(2, Name = @"tipper")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Tipper { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuxSignerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"sign_doc")]
        public SignDocDirectAux SignDoc { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mode")]
        public global::cosmos.tx.signing.v1beta1.SignMode Mode { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sig")]
        public byte[] Sig { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
