// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: orm.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.orm.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TableDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"primary_key")]
        public PrimaryKeyDescriptor PrimaryKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public global::System.Collections.Generic.List<SecondaryIndexDescriptor> Indexs { get; } = new global::System.Collections.Generic.List<SecondaryIndexDescriptor>();

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrimaryKeyDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fields")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Fields { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"auto_increment")]
        public bool AutoIncrement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SecondaryIndexDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fields")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Fields { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"unique")]
        public bool Unique { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SingletonDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

    }

    public static partial class Extensions
    {
        public static TableDescriptor GetTable(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<TableDescriptor>(obj, 104503790);

        public static void SetTable(this global::Google.Protobuf.Reflection.MessageOptions obj, TableDescriptor value)
            => global::ProtoBuf.Extensible.AppendValue<TableDescriptor>(obj, 104503790, value);

        public static SingletonDescriptor GetSingleton(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<SingletonDescriptor>(obj, 104503791);

        public static void SetSingleton(this global::Google.Protobuf.Reflection.MessageOptions obj, SingletonDescriptor value)
            => global::ProtoBuf.Extensible.AppendValue<SingletonDescriptor>(obj, 104503791, value);

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
