// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: snapshot.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos._base.snapshots.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Snapshot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"height")]
        public ulong Height { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"format")]
        public uint Format { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"chunks")]
        public uint Chunks { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hash")]
        public byte[] Hash { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"metadata")]
        public Metadata Metadata { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Metadata : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chunk_hashes")]
        public global::System.Collections.Generic.List<byte[]> ChunkHashes { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"store")]
        public SnapshotStoreItem Store
        {
            get { return __pbn__item.Is(1) ? ((SnapshotStoreItem)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeStore() => __pbn__item.Is(1);
        public void ResetStore() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__item;

        [global::ProtoBuf.ProtoMember(2, Name = @"iavl")]
        public SnapshotIAVLItem Iavl
        {
            get { return __pbn__item.Is(2) ? ((SnapshotIAVLItem)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeIavl() => __pbn__item.Is(2);
        public void ResetIavl() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"extension")]
        public SnapshotExtensionMeta Extension
        {
            get { return __pbn__item.Is(3) ? ((SnapshotExtensionMeta)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeExtension() => __pbn__item.Is(3);
        public void ResetExtension() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"extension_payload")]
        public SnapshotExtensionPayload ExtensionPayload
        {
            get { return __pbn__item.Is(4) ? ((SnapshotExtensionPayload)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeExtensionPayload() => __pbn__item.Is(4);
        public void ResetExtensionPayload() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"kv")]
        public SnapshotKVItem Kv
        {
            get { return __pbn__item.Is(5) ? ((SnapshotKVItem)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeKv() => __pbn__item.Is(5);
        public void ResetKv() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"schema")]
        public SnapshotSchema Schema
        {
            get { return __pbn__item.Is(6) ? ((SnapshotSchema)__pbn__item.Object) : default; }
            set { __pbn__item = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeSchema() => __pbn__item.Is(6);
        public void ResetSchema() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__item, 6);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotStoreItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotIAVLItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public byte[] Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public byte[] Value { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"version")]
        public long Version { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"height")]
        public int Height { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotExtensionMeta : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"format")]
        public uint Format { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotExtensionPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"payload")]
        public byte[] Payload { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotKVItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public byte[] Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SnapshotSchema : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"keys")]
        public global::System.Collections.Generic.List<byte[]> Keys { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
