// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: genesis.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.nft.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GenesisState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"classes")]
        public global::System.Collections.Generic.List<Class> Classes { get; } = new global::System.Collections.Generic.List<Class>();

        [global::ProtoBuf.ProtoMember(2, Name = @"entries")]
        public global::System.Collections.Generic.List<Entry> Entries { get; } = new global::System.Collections.Generic.List<Entry>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Entry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"owner")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Owner { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"nfts")]
        public global::System.Collections.Generic.List<Nft> Nfts { get; } = new global::System.Collections.Generic.List<Nft>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
