// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: feegrant.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cosmos.feegrant.v1beta1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BasicAllowance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spend_limit")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> SpendLimits { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(2, Name = @"expiration")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? Expiration { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeriodicAllowance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"basic")]
        public BasicAllowance Basic { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"period")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? Period { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"period_spend_limit")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> PeriodSpendLimits { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(4, Name = @"period_can_spend")]
        public global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin> PeriodCanSpends { get; } = new global::System.Collections.Generic.List<global::cosmos._base.v1beta1.Coin>();

        [global::ProtoBuf.ProtoMember(5, Name = @"period_reset")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? PeriodReset { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AllowedMsgAllowance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"allowance")]
        public global::Google.Protobuf.WellKnownTypes.Any Allowance { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allowed_messages")]
        public global::System.Collections.Generic.List<string> AllowedMessages { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Grant : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"granter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Granter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"grantee")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Grantee { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"allowance")]
        public global::Google.Protobuf.WellKnownTypes.Any Allowance { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
